"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { ImageUp, RotateCcw } from "lucide-react";
import { useRouter } from "next/navigation";
import { AvatarMark } from "@/components/layout/avatar-mark";

interface Props {name:string;email:string;jobTitle:string;initialImageUrl:string|null;hasCustomImage:boolean;driveConnected:boolean;setup?:boolean}

export function ProfileSettingsPage({name,email,jobTitle,initialImageUrl,hasCustomImage,driveConnected,setup=false}:Props){
  const router=useRouter();
  const [preview,setPreview]=useState(initialImageUrl),[custom,setCustom]=useState(hasCustomImage),[displayName,setDisplayName]=useState(name),[title,setTitle]=useState(jobTitle),[pending,setPending]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>()=>{if(preview?.startsWith("blob:"))URL.revokeObjectURL(preview)},[preview]);
  const select=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setMessage("JPG, PNG, WebP 이미지를 5MB 이하로 선택해주세요.");return}const local=URL.createObjectURL(file);setPreview(local);setPending(true);setMessage("");const form=new FormData();form.set("image",file);const response=await fetch("/api/profile/avatar",{method:"POST",body:form});setPending(false);if(!response.ok){URL.revokeObjectURL(local);setPreview(initialImageUrl);setMessage(response.status===409?"먼저 OWNER가 Workspace Google Drive를 연결해주세요.":"사진을 업로드하지 못했습니다.");return}const result=await response.json() as {imageUrl:string};setPreview(`${result.imageUrl}${result.imageUrl.includes("?")?"&":"?"}client=${Date.now()}`);setCustom(true);setMessage("프로필 사진을 변경했습니다.");router.refresh()};
  const reset=async()=>{setPending(true);setMessage("");const response=await fetch("/api/profile/avatar",{method:"DELETE"});const result=await response.json().catch(()=>({})) as {imageUrl?:string|null};setPending(false);if(!response.ok){setMessage("사진을 되돌리지 못했습니다.");return}setPreview(result.imageUrl??null);setCustom(false);setMessage("Google 프로필 사진으로 되돌렸습니다.");router.refresh()};
  const save=async(event:FormEvent)=>{event.preventDefault();const nextName=displayName.trim(),nextTitle=title.trim();if(!nextName||!nextTitle){setMessage("이름과 직급을 모두 입력해주세요.");return}setPending(true);setMessage("");const response=await fetch("/api/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:nextName,jobTitle:nextTitle,complete:true})});setPending(false);if(!response.ok){setMessage("프로필을 저장하지 못했습니다.");return}if(setup){router.replace("/dashboard");router.refresh();return}setMessage("프로필을 저장했습니다.");router.refresh()};
  return <section className={`profile-settings-page${setup?" is-setup":""}`}><header><p>PROFILE</p><h1>{setup?"프로필을 설정해주세요":"프로필 설정"}</h1><span>{setup?"함께 일하는 팀원들에게 표시될 정보를 입력해주세요.":"Workspace에 표시되는 내 정보를 관리합니다."}</span></header><article><div className="profile-avatar-preview"><AvatarMark imageUrl={preview??undefined}/></div><div className="profile-account"><h2>{displayName||name}</h2><p>{email}</p><span>JPG, PNG, WebP · 최대 5MB</span></div><div className="profile-actions"><label className={pending||!driveConnected?"is-disabled":""}><ImageUp/>사진 선택<input type="file" accept="image/jpeg,image/png,image/webp" disabled={pending||!driveConnected} onChange={(event)=>void select(event)}/></label><button type="button" disabled={pending||!custom} onClick={()=>void reset()}><RotateCcw/>Google 사진으로 되돌리기</button></div>{!driveConnected&&<p className="profile-warning">현재 Google 프로필 사진을 사용합니다. 사진 변경은 Workspace Drive 연결 후 가능합니다.</p>}<form className="profile-fields" onSubmit={(event)=>void save(event)}><label><span>이름 <strong>필수</strong></span><input required maxLength={40} autoComplete="name" placeholder="이름을 입력해주세요" value={displayName} onChange={(event)=>setDisplayName(event.target.value)}/></label><label><span>직급 <strong>필수</strong></span><input required maxLength={40} placeholder="예: 대표, 실장, 디자이너" value={title} onChange={(event)=>setTitle(event.target.value)}/><small>표시용 직급이며 Workspace 권한과는 별개입니다.</small></label><button type="submit" disabled={pending}>{pending?"저장 중…":setup?"설정 완료":"저장"}</button></form>{message&&<p className="profile-message" role="status">{message}</p>}</article></section>;
}
