const API="https://sheets.googleapis.com/v4/spreadsheets";
async function sheetsFetch(token:string,path:string,init?:RequestInit){return fetch(`${API}${path}`,{...init,headers:{authorization:`Bearer ${token}`,...(init?.body?{"content-type":"application/json"}:{}),...init?.headers},cache:"no-store",signal:AbortSignal.timeout(30_000)});}
export async function initializeConsultationSpreadsheet(token:string,id:string,summaryHeaders:string[],rawHeaders:string[]){const meta=await sheetsFetch(token,`/${encodeURIComponent(id)}?fields=sheets.properties`);if(!meta.ok)throw new Error(meta.status===403?"google_permission_required":"sheets_initialize_failed");const sheets=(await meta.json() as {sheets?:{properties:{sheetId:number;title:string}}[]}).sheets??[];const requests:unknown[]=[];if(!sheets.some((s)=>s.properties.title==="상담 접수대장")){const first=sheets[0];if(first)requests.push({updateSheetProperties:{properties:{sheetId:first.properties.sheetId,title:"상담 접수대장"},fields:"title"}});else requests.push({addSheet:{properties:{title:"상담 접수대장"}}});}if(!sheets.some((s)=>s.properties.title==="체크리스트 원본"))requests.push({addSheet:{properties:{title:"체크리스트 원본"}}});if(requests.length){const r=await sheetsFetch(token,`/${encodeURIComponent(id)}:batchUpdate`,{method:"POST",body:JSON.stringify({requests})});if(!r.ok)throw new Error(r.status===403?"google_permission_required":"sheets_initialize_failed");}if(!await hasConsultationRow(token,id,"상담 접수대장","상담ID"))await appendRows(token,id,"상담 접수대장",[summaryHeaders]);else await ensureConfirmedScheduleHeader(token,id);if(!await hasConsultationRow(token,id,"체크리스트 원본","상담ID"))await appendRows(token,id,"체크리스트 원본",[rawHeaders]);}
export async function appendRows(token:string,id:string,sheet:string,rows:unknown[][]){const range=encodeURIComponent(`'${sheet}'!A:ZZ`);const r=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${range}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values:rows})});if(!r.ok)throw new Error(r.status===403?"google_permission_required":"sheets_append_failed");}
export async function hasConsultationRow(token:string,id:string,sheet:string,consultationId:string){const range=encodeURIComponent(`'${sheet}'!A:A`);const r=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${range}`);if(!r.ok)throw new Error(r.status===403?"google_permission_required":"sheets_read_failed");return ((await r.json() as {values?:string[][]}).values??[]).some((row)=>row[0]===consultationId);}
export async function updateStatusCell(token:string,id:string,consultationId:string,status:string){const range=encodeURIComponent("'상담 접수대장'!A:J");const read=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${range}`);if(!read.ok)throw new Error(read.status===403?"google_permission_required":"sheets_read_failed");const rows=(await read.json() as {values?:string[][]}).values??[];const index=rows.findIndex((row)=>row[0]===consultationId);if(index<1)throw new Error("sheet_row_missing");const cell=encodeURIComponent(`'상담 접수대장'!J${index+1}`);const write=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${cell}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values:[[status]]})});if(!write.ok)throw new Error(write.status===403?"google_permission_required":"sheets_update_failed");}

async function ensureConfirmedScheduleHeader(token:string,id:string){const range=encodeURIComponent("'상담 접수대장'!K1");const read=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${range}`);if(!read.ok)throw new Error(read.status===403?"google_permission_required":"sheets_read_failed");const value=((await read.json() as {values?:string[][]}).values??[])[0]?.[0];if(value==="확정 상담일시")return;const write=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${range}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values:[["확정 상담일시"]]})});if(!write.ok)throw new Error(write.status===403?"google_permission_required":"sheets_update_failed");}

export async function updateStatusAndScheduleCells(token:string,id:string,consultationId:string,status:string,scheduledAt:string){await ensureConfirmedScheduleHeader(token,id);const range=encodeURIComponent("'상담 접수대장'!A:K");const read=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${range}`);if(!read.ok)throw new Error(read.status===403?"google_permission_required":"sheets_read_failed");const rows=(await read.json() as {values?:string[][]}).values??[];const index=rows.findIndex((row)=>row[0]===consultationId);if(index<1)throw new Error("sheet_row_missing");const target=encodeURIComponent(`'상담 접수대장'!J${index+1}:K${index+1}`);const write=await sheetsFetch(token,`/${encodeURIComponent(id)}/values/${target}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values:[[status,scheduledAt]]})});if(!write.ok)throw new Error(write.status===403?"google_permission_required":"sheets_update_failed");}
