import { getDb } from "@/lib/db/client";
import type { LostReason } from "@/types/consultation";

export type AnalyticsPeriod="this-month"|"last-month"|"three-months"|"this-year";
export interface AnalyticsRow {id:string;assignedUserId:string|null;assignedUserName:string|null;quoteAmount:number|null;quoteStatus:"NOT_CREATED"|"DRAFT"|"SENT";contractOutcome:"PENDING"|"CONTRACTED"|"LOST";lostReason:LostReason|null;reserved:number;completed:number}
export interface AnalyticsMember {userId:string;name:string}
export interface AnalyticsData {rows:AnalyticsRow[];members:AnalyticsMember[];from:string;to:string}

const seoulParts=(date:Date)=>{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const get=(type:Intl.DateTimeFormatPartTypes)=>Number(parts.find((part)=>part.type===type)?.value);return {year:get("year"),month:get("month"),day:get("day")}};
const utcFromSeoul=(year:number,month:number,day:number)=>new Date(Date.UTC(year,month-1,day,-9)).toISOString();
export function analyticsRange(period:AnalyticsPeriod,now=new Date()){const current=seoulParts(now),fromYear=current.year,toYear=current.year;let fromMonth=current.month,toMonth=current.month+1;if(period==="last-month"){fromMonth-=1;toMonth=current.month}else if(period==="three-months")fromMonth-=2;else if(period==="this-year"){fromMonth=1;toMonth=13}const normalize=(year:number,month:number)=>{const value=new Date(Date.UTC(year,month-1,1));return {year:value.getUTCFullYear(),month:value.getUTCMonth()+1}};const from=normalize(fromYear,fromMonth),to=normalize(toYear,toMonth);return {from:utcFromSeoul(from.year,from.month,1),to:utcFromSeoul(to.year,to.month,1)}};

export async function getAnalyticsData(workspaceId:string,period:AnalyticsPeriod):Promise<AnalyticsData>{
  const {from,to}=analyticsRange(period),db=await getDb();
  const rows=await db.prepare(`SELECT c.id,c.assigned_user_id,CASE WHEN u.id IS NULL THEN NULL ELSE COALESCE(NULLIF(u.display_name,''),u.google_name,u.email) END AS assigned_user_name,c.quote_amount,c.quote_status,c.contract_outcome,c.lost_reason,CASE WHEN c.scheduled_at IS NOT NULL OR EXISTS(SELECT 1 FROM consultation_events e WHERE e.consultation_id=c.id AND e.event_type IN ('RESERVATION_CREATED','RESERVATION_UPDATED')) THEN 1 ELSE 0 END AS reserved,CASE WHEN c.status IN ('COMPLETED','CONTRACTED') OR c.quote_status<>'NOT_CREATED' OR EXISTS(SELECT 1 FROM consultation_events e WHERE e.consultation_id=c.id AND e.event_type='STATUS_CHANGED' AND json_extract(e.event_payload_json,'$.to')='COMPLETED') THEN 1 ELSE 0 END AS completed FROM consultations c LEFT JOIN users u ON u.id=c.assigned_user_id WHERE c.workspace_id=? AND julianday(c.submitted_at)>=julianday(?) AND julianday(c.submitted_at)<julianday(?) ORDER BY c.submitted_at DESC`).bind(workspaceId,from,to).all<{id:string;assigned_user_id:string|null;assigned_user_name:string|null;quote_amount:number|null;quote_status:AnalyticsRow["quoteStatus"];contract_outcome:AnalyticsRow["contractOutcome"];lost_reason:LostReason|null;reserved:number;completed:number}>();
  const members=await db.prepare(`SELECT u.id AS user_id,COALESCE(NULLIF(u.display_name,''),u.google_name,u.email) AS name FROM workspace_members wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=? AND wm.status='ACTIVE' AND u.status='ACTIVE' ORDER BY name`).bind(workspaceId).all<{user_id:string;name:string}>();
  return {rows:rows.results.map((row)=>({id:row.id,assignedUserId:row.assigned_user_id,assignedUserName:row.assigned_user_name,quoteAmount:row.quote_amount,quoteStatus:row.quote_status,contractOutcome:row.contract_outcome,lostReason:row.lost_reason,reserved:row.reserved,completed:row.completed})),members:members.results.map((member)=>({userId:member.user_id,name:member.name})),from,to};
}
