"use client";

import { useState } from "react";
import { Copy,UserMinus,Users } from "lucide-react";
import type { TeamInvitation,TeamMember } from "@/lib/workspaces/team-repository";

export function TeamManagementPage({workspaceName,isOwner,initialMembers,initialInvitations}:{workspaceName:string;isOwner:boolean;initialMembers:TeamMember[];initialInvitations:TeamInvitation[]}){
  const [members,setMembers]=useState(initialMembers),[invitations,setInvitations]=useState(initialInvitations),[email,setEmail]=useState(""),[inviteUrl,setInviteUrl]=useState(""),[status,setStatus]=useState(""),[pending,setPending]=useState(false);
  const invite=async()=>{setPending(true);setStatus("");const response=await fetch("/api/team/invitations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const result=await response.json() as {invitation?:{id:string;email:string;inviteUrl:string};error?:string};setPending(false);if(!response.ok||!result.invitation){setStatus(result.error==="already_member"?"이미 참여 중인 팀원입니다.":"초대를 만들지 못했습니다.");return}setInviteUrl(result.invitation.inviteUrl);setInvitations((items)=>[{id:result.invitation!.id,email:result.invitation!.email,status:"PENDING",expiresAt:new Date(Date.now()+7*86400000).toISOString(),createdAt:new Date().toISOString()},...items]);setEmail("");setStatus("초대 링크를 생성했습니다.")};
  const remove=async(member:TeamMember)=>{const message=member.assignedCount?`담당 중인 상담 ${member.assignedCount}건이 미지정 상태로 변경됩니다. 팀에서 제거할까요?`:"이 팀원을 Workspace에서 제거할까요?";if(!window.confirm(message))return;const response=await fetch(`/api/team/members/${encodeURIComponent(member.membershipId)}`,{method:"DELETE"});if(!response.ok){setStatus("팀원을 제거하지 못했습니다.");return}setMembers((items)=>items.map((item)=>item.membershipId===member.membershipId?{...item,status:"REMOVED",assignedCount:0}:item));setStatus("팀원을 제거했습니다.")};
  return <div className="team-page"><header><div><p>TEAM</p><h1>팀 관리</h1><span>{workspaceName}에서 함께 상담을 관리하는 팀원입니다.</span></div><div className="team-count"><Users/><strong>{members.filter((member)=>member.status==="ACTIVE").length}</strong><span>명 참여 중</span></div></header>
    {isOwner&&<section className="team-invite"><h2>팀원 초대</h2><p>Google 계정 이메일로 초대 링크를 만듭니다. 링크를 직접 전달해주세요.</p><div><input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="example@gmail.com"/><button type="button" disabled={pending||!email.trim()} onClick={()=>void invite()}>{pending?"생성 중…":"초대하기"}</button></div>{inviteUrl&&<div className="invite-link"><input readOnly value={inviteUrl}/><button type="button" onClick={()=>void navigator.clipboard.writeText(inviteUrl)}><Copy/> 복사</button></div>}{status&&<p className="team-status" role="status">{status}</p>}</section>}
    <section className="team-members"><header><h2>팀원</h2><span>OWNER는 제거할 수 없습니다.</span></header><div className="team-table"><div className="team-row team-row-head"><span>이름</span><span>이메일</span><span>역할</span><span>참여 상태</span><span/></div>{members.map((member)=><div className="team-row" key={member.membershipId}><strong>{member.name}</strong><span>{member.email}</span><span>{member.role}</span><span className={`member-status member-${member.status.toLowerCase()}`}>{member.status}</span><span>{isOwner&&member.role==="MEMBER"&&member.status==="ACTIVE"&&<button type="button" aria-label={`${member.name} 제거`} onClick={()=>void remove(member)}><UserMinus/> 제거</button>}</span></div>)}</div></section>
    {isOwner&&invitations.some((item)=>item.status==="PENDING")&&<section className="team-invitations"><h2>대기 중인 초대</h2>{invitations.filter((item)=>item.status==="PENDING").map((item)=><div key={item.id}><strong>{item.email}</strong><span>{new Date(item.expiresAt).toLocaleDateString("ko-KR")} 만료</span></div>)}</section>}
  </div>;
}
