import { getDb } from "@/lib/db/client";
import type { TodoItem } from "@/types/dashboard";

interface Row{id:string;label:string;completed:number;created_at:string;updated_at:string}
const map=(row:Row):TodoItem=>({id:row.id,label:row.label,completed:row.completed===1,createdAt:row.created_at,updatedAt:row.updated_at});
export async function listTodos(workspaceId:string,userId:string):Promise<TodoItem[]>{const result=await (await getDb()).prepare(`SELECT id,label,completed,created_at,updated_at FROM user_todos WHERE workspace_id=? AND user_id=? ORDER BY completed ASC,created_at DESC LIMIT 200`).bind(workspaceId,userId).all<Row>();return result.results.map(map)}
export async function createTodo(workspaceId:string,userId:string,label:string):Promise<TodoItem>{const db=await getDb(),id=crypto.randomUUID(),value=label.trim();await db.prepare(`INSERT INTO user_todos(id,workspace_id,user_id,label) VALUES(?,?,?,?)`).bind(id,workspaceId,userId,value).run();const row=await db.prepare(`SELECT id,label,completed,created_at,updated_at FROM user_todos WHERE id=? AND workspace_id=? AND user_id=?`).bind(id,workspaceId,userId).first<Row>();if(!row)throw new Error("todo_create_failed");return map(row)}
export async function toggleTodo(workspaceId:string,userId:string,id:string,completed:boolean):Promise<TodoItem|null>{const db=await getDb();await db.prepare(`UPDATE user_todos SET completed=?,completed_at=CASE WHEN ?=1 THEN datetime('now') ELSE NULL END,updated_at=datetime('now') WHERE id=? AND workspace_id=? AND user_id=?`).bind(completed?1:0,completed?1:0,id,workspaceId,userId).run();const row=await db.prepare(`SELECT id,label,completed,created_at,updated_at FROM user_todos WHERE id=? AND workspace_id=? AND user_id=?`).bind(id,workspaceId,userId).first<Row>();return row?map(row):null}
export async function deleteTodo(workspaceId:string,userId:string,id:string):Promise<boolean>{const result=await (await getDb()).prepare(`DELETE FROM user_todos WHERE id=? AND workspace_id=? AND user_id=?`).bind(id,workspaceId,userId).run();return result.meta.changes===1}
