import Link from "next/link";
import { ArrowRight } from "lucide-react";
import type { AnalyticsData,AnalyticsPeriod } from "@/lib/analytics/analytics-repository";
import { lostReasonLabel } from "@/lib/consultations/quote-display";

const periods:[AnalyticsPeriod,string][]=[["this-month","이번 달"],["last-month","지난 달"],["three-months","최근 3개월"],["this-year","올해"]];
const number=(value:number)=>value.toLocaleString("ko-KR");
const percent=(top:number,bottom:number)=>bottom?`${(top/bottom*100).toFixed(1)}%`:"—";
const amount=(value:number)=>`${Math.round(value/10000).toLocaleString("ko-KR")}만원`;

export function AnalyticsPage({data,period}:{data:AnalyticsData;period:AnalyticsPeriod}){
  const received=data.rows.length,completed=data.rows.filter((row)=>row.completed).length,sent=data.rows.filter((row)=>row.quoteStatus==="SENT").length,contracted=data.rows.filter((row)=>row.contractOutcome==="CONTRACTED").length,pending=data.rows.filter((row)=>row.quoteStatus==="SENT"&&row.contractOutcome==="PENDING").length,lost=data.rows.filter((row)=>row.contractOutcome==="LOST").length,decided=contracted+lost;
  const reserved=data.rows.filter((row)=>row.reserved).length;
  const quotes=data.rows.filter((row):row is typeof row&{quoteAmount:number}=>row.quoteAmount!==null),contracts=data.rows.filter((row):row is typeof row&{quoteAmount:number}=>row.contractOutcome==="CONTRACTED"&&row.quoteAmount!==null);
  const contractTotal=contracts.reduce((sum,row)=>sum+row.quoteAmount,0),quoteAverage=quotes.length?quotes.reduce((sum,row)=>sum+row.quoteAmount,0)/quotes.length:0,contractAverage=contracts.length?contractTotal/contracts.length:0;
  const headline=[{label:"접수",value:received},{label:"상담 완료",value:completed},{label:"견적 발송",value:sent},{label:"계약",value:contracted,tone:"positive"},{label:"결정 대기",value:pending},{label:"불성사",value:lost,tone:"negative"}];
  const funnel=[{label:"접수",value:received},{label:"예약",value:reserved},{label:"상담 완료",value:completed},{label:"견적 발송",value:sent},{label:"계약",value:contracted}];
  const reasons=Object.entries(lostReasonLabel).map(([reason,label])=>({reason,label,count:data.rows.filter((row)=>row.contractOutcome==="LOST"&&row.lostReason===reason).length})).filter((item)=>item.count).sort((a,b)=>b.count-a.count);
  const memberRows=data.members.map((member)=>{const rows=data.rows.filter((row)=>row.assignedUserId===member.userId),memberContract=rows.filter((row)=>row.contractOutcome==="CONTRACTED").length,memberLost=rows.filter((row)=>row.contractOutcome==="LOST").length;return {id:member.userId,name:member.name,completed:rows.filter((row)=>row.completed).length,sent:rows.filter((row)=>row.quoteStatus==="SENT").length,contracted:memberContract,lost:memberLost,rate:percent(memberContract,memberContract+memberLost)}});
  if(data.rows.some((row)=>!row.assignedUserId)){const rows=data.rows.filter((row)=>!row.assignedUserId),memberContract=rows.filter((row)=>row.contractOutcome==="CONTRACTED").length,memberLost=rows.filter((row)=>row.contractOutcome==="LOST").length;memberRows.push({id:"unassigned",name:"미지정",completed:rows.filter((row)=>row.completed).length,sent:rows.filter((row)=>row.quoteStatus==="SENT").length,contracted:memberContract,lost:memberLost,rate:percent(memberContract,memberContract+memberLost)})}
  return <main className="analytics-page"><header><div><p>OPERATIONS ANALYTICS</p><h1>운영 분석</h1><span>선택 기간 내 접수된 상담의 단계별 성과입니다.</span></div><nav aria-label="분석 기간">{periods.map(([value,label])=><Link className={period===value?"is-active":""} href={`/analytics?period=${value}`} key={value}>{label}</Link>)}</nav></header><section className="analytics-headline" aria-label="핵심 지표">{headline.map((item)=><div className={item.tone?`is-${item.tone}`:""} key={item.label}><span>{item.label}</span><strong>{number(item.value)}<small>건</small></strong></div>)}<div className="is-rate"><span>계약률</span><strong>{percent(contracted,decided)}</strong><small>계약 ÷ 계약·불성사</small></div></section><section className="analytics-section"><header><div><h2>상담 전환 흐름</h2><p>동일 기간 접수 상담이 각 단계에 도달한 기준</p></div></header><div className="conversion-flow">{funnel.map((step,index)=><div className="conversion-step-wrap" key={step.label}><div className="conversion-step"><span>{step.label}</span><strong>{number(step.value)}<small>건</small></strong>{index>0&&<em>이전 단계 대비 {percent(step.value,funnel[index-1].value)}</em>}</div>{index<funnel.length-1&&<ArrowRight/>}</div>)}</div></section><div className="analytics-split"><section className="analytics-section loss-analysis"><header><div><h2>불성사 분석</h2><p>불성사 {number(lost)}건의 사유</p></div></header>{reasons.length?<div>{reasons.map((item)=><div key={item.reason}><span>{item.label}</span><i><b style={{width:`${lost?item.count/lost*100:0}%`}}/></i><strong>{item.count}건 <small>{percent(item.count,lost)}</small></strong></div>)}</div>:<p className="analytics-empty">기간 내 불성사 상담이 없습니다.</p>}</section><section className="analytics-section amount-analysis"><header><div><h2>견적금액</h2><p>실제 수금·매출이 아닌 등록된 견적 기준</p></div></header><dl><div><dt>계약된 견적 총액</dt><dd>{amount(contractTotal)}</dd></div><div><dt>평균 견적금액</dt><dd>{quotes.length?amount(quoteAverage):"—"}</dd></div><div><dt>평균 계약금액</dt><dd>{contracts.length?amount(contractAverage):"—"}</dd></div></dl></section></div><section className="analytics-section member-analysis"><header><div><h2>담당자별 성과</h2><p>기간 내 접수 상담의 현재 담당자 기준</p></div></header><div className="analytics-table-wrap"><table><thead><tr><th>담당자</th><th>상담 완료</th><th>견적 발송</th><th>계약</th><th>불성사</th><th>계약률</th></tr></thead><tbody>{memberRows.map((member)=><tr key={member.id}><th>{member.name}</th><td>{member.completed}건</td><td>{member.sent}건</td><td>{member.contracted}건</td><td>{member.lost}건</td><td><strong>{member.rate}</strong></td></tr>)}</tbody></table></div></section></main>;
}
