"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import type { ChecklistReview } from "@/lib/consultations/checklist-review-repository";
import { consultationDetailPath, consultationChecklistPath } from "@/lib/consultations/consultation-routes";

type Field = { section: string; questionKey: string; label: string; answer: string };
type SaveState = "idle" | "saving" | "saved" | "error";
type Filter = "all" | "checked" | "unchecked" | "confirmed";
const emptyReview=(key:string):ChecklistReview=>({questionKey:key,isChecked:false,isConfirmed:false,consultationNote:"",updatedByName:null,updatedAt:""});

export function ConsultationSession({ consultationId, customerName, meta, fields, initialReviews }: { consultationId: string; customerName: string; meta: string; fields: Field[]; initialReviews: ChecklistReview[] }) {
  const [reviews,setReviews]=useState<Record<string,ChecklistReview>>(Object.fromEntries(initialReviews.map((review)=>[review.questionKey,review]))),[states,setStates]=useState<Record<string,SaveState>>({}),[filter,setFilter]=useState<Filter>("all"),[summary,setSummary]=useState<SaveState>("idle"),[summaryMessage,setSummaryMessage]=useState("");
  const timers=useRef<Record<string,ReturnType<typeof setTimeout>>>({}),pageRef=useRef<HTMLElement>(null);
  useEffect(()=>()=>Object.values(timers.current).forEach(clearTimeout),[]);
  const preserveScroll=(change:()=>void)=>{const scroller=pageRef.current?.closest(".main-content") as HTMLElement|null,top=scroller?.scrollTop??window.scrollY;change();requestAnimationFrame(()=>{if(scroller)scroller.scrollTop=top;else window.scrollTo({top});requestAnimationFrame(()=>{if(scroller)scroller.scrollTop=top;else window.scrollTo({top})})})};
  const save=async(key:string,isChecked:boolean,isConfirmed:boolean,note:string)=>{setStates((value)=>({...value,[key]:"saving"}));try{const response=await fetch(`/api/consultations/${encodeURIComponent(consultationId)}/checklist-reviews`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({questionKey:key,isChecked,isConfirmed,consultationNote:note})}),data=await response.json() as {review?:ChecklistReview};if(!response.ok||!data.review)throw new Error();setReviews((value)=>({...value,[key]:data.review!}));setStates((value)=>({...value,[key]:"saved"}));return true}catch{setStates((value)=>({...value,[key]:"error"}));return false}};
  const changeNote=(field:Field,note:string)=>{const current=reviews[field.questionKey]??emptyReview(field.questionKey);setReviews((value)=>({...value,[field.questionKey]:{...current,consultationNote:note}}));setStates((value)=>({...value,[field.questionKey]:"idle"}));clearTimeout(timers.current[field.questionKey]);timers.current[field.questionKey]=setTimeout(()=>void save(field.questionKey,current.isChecked,current.isConfirmed,note),700)};
  const setQuestionState=(field:Field,next:"unchecked"|"checked"|"confirmed")=>{clearTimeout(timers.current[field.questionKey]);const current=reviews[field.questionKey]??emptyReview(field.questionKey),updated={...current,isChecked:next!=="unchecked",isConfirmed:next==="confirmed"};preserveScroll(()=>setReviews((value)=>({...value,[field.questionKey]:updated})));void save(field.questionKey,updated.isChecked,updated.isConfirmed,updated.consultationNote)};
  const counts=useMemo(()=>fields.reduce((value,field)=>{const review=reviews[field.questionKey];if(review?.isConfirmed)value.confirmed++;else if(review?.isChecked)value.checked++;else value.unchecked++;return value},{checked:0,unchecked:0,confirmed:0}),[fields,reviews]);
  const visible=useMemo(()=>fields.filter((field)=>{const review=reviews[field.questionKey];if(filter==="checked")return Boolean(review?.isChecked&&!review.isConfirmed);if(filter==="unchecked")return !review?.isChecked&&!review?.isConfirmed;if(filter==="confirmed")return Boolean(review?.isConfirmed);return true}),[filter,fields,reviews]);
  const questionNumbers=useMemo(()=>new Map(fields.map((field,index)=>[field.questionKey,index+1])),[fields]);
  const summarize=async()=>{Object.values(timers.current).forEach(clearTimeout);setSummary("saving");setSummaryMessage("");const payload=fields.map((field)=>{const review=reviews[field.questionKey]??emptyReview(field.questionKey);return {questionKey:field.questionKey,isChecked:review.isChecked,isConfirmed:review.isConfirmed,consultationNote:review.consultationNote}});try{const response=await fetch(`/api/consultations/${encodeURIComponent(consultationId)}/checklist-reviews`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reviews:payload})}),data=await response.json() as {pdf?:{saved?:boolean;error?:string}};if(!response.ok)throw new Error();setSummary("saved");setSummaryMessage(data.pdf?.saved?"상담 요약과 상담 기록 PDF를 저장했습니다.":"상담 요약은 저장했지만 PDF는 저장하지 못했습니다. Drive 연결을 확인해주세요.")}catch{setSummary("error");setSummaryMessage("상담 내용을 저장하지 못했습니다. 작성 내용은 화면에 유지됩니다.")}};
  const filters:Array<[Filter,string]>=[["all","전체"],["checked","체크"],["unchecked","미체크"],["confirmed","확인완료"]];
  return <main ref={pageRef} className="consultation-session-page"><header className="consultation-session-header"><div><p>CONSULTATION SESSION</p><h1>{customerName} 고객 상담</h1><span>{meta}</span></div><div><strong>체크 {counts.checked} · 미체크 {counts.unchecked} · 확인완료 {counts.confirmed}</strong><nav><Link href={consultationDetailPath(consultationId)}>고객 상세</Link><Link href={consultationChecklistPath(consultationId)}>상담지 원본</Link></nav></div></header>
    <div className="session-filter" aria-label="상담 질문 상태 필터">{filters.map(([value,label])=><button key={value} className={filter===value?"is-active":""} onClick={()=>setFilter(value)} type="button">{label}</button>)}</div>
    <article className="session-document">{visible.map((field,index)=>{const showSection=index===0||visible[index-1].section!==field.section,review=reviews[field.questionKey]??emptyReview(field.questionKey),state=states[field.questionKey]??"idle",status=review.isConfirmed?"confirmed":review.isChecked?"checked":"unchecked",number=String(questionNumbers.get(field.questionKey)??index+1).padStart(2,"0"),hasNote=Boolean(review.consultationNote.trim());return <div key={field.questionKey}>{showSection&&<h2>{field.section}</h2>}<section className={`session-question is-${status}${hasNote?" has-note":""}`}><header className="session-question-header"><input type="checkbox" checked={status!=="unchecked"} disabled={status==="confirmed"} onChange={()=>setQuestionState(field,status==="unchecked"?"checked":"unchecked")} aria-label={`${number}. ${field.label} 추가 확인 대상`} /><h3><span>{number}.</span> {field.label}</h3>{status==="confirmed"&&<em>확인완료</em>}{hasNote&&<em className="has-note-label">메모 있음</em>}</header><div className="session-customer-answer"><span>고객 답변</span><p>{field.answer}</p></div>{status!=="unchecked"&&<div className="session-note-area"><label className="session-note"><span>상담 메모</span><textarea maxLength={4000} value={review.consultationNote} onChange={(event)=>changeNote(field,event.target.value)} placeholder="상담 중 추가로 확인한 내용을 입력해주세요."/><small>{state==="saving"?"저장 중...":state==="saved"?"저장됨":state==="error"?"저장 실패 · 작성 내용은 유지됩니다.":review.updatedByName?`${review.updatedByName} 수정`:"자동 저장"}</small></label><button className="session-confirm-action" type="button" onClick={()=>setQuestionState(field,status==="confirmed"?"checked":"confirmed")}>{status==="confirmed"?"다시 확인":"확인 완료"}</button></div>}</section></div>})}{!visible.length&&<p className="session-empty">해당 상태의 상담 항목이 없습니다.</p>}</article>
    <footer className="session-summary-action"><div><strong>상담 기록을 저장할까요?</strong><span>질문 상태와 메모를 최종 저장하고 상세 요약과 Drive PDF를 업데이트합니다.</span></div><button disabled={summary==="saving"} type="button" onClick={()=>void summarize()}>{summary==="saving"?"저장 중...":"상담 저장"}</button>{summaryMessage&&<p className={summary==="error"?"is-error":""}>{summaryMessage}</p>}</footer></main>;
}
