"use client";

import { useState } from "react";
import { X } from "lucide-react";
import type { Consultation,ContractOutcome,LostReason } from "@/types/consultation";
import { lostReasonLabel } from "@/lib/consultations/quote-display";

export type OutcomeChanged={outcome:Exclude<ContractOutcome,"PENDING">;lostReason:LostReason|null;lostReasonNote:string|null;decidedAt:string;status:"완료"|"계약"};
export function ContractOutcomeEditor({consultation,initialMode,onClose,onChanged}:{consultation:Consultation;initialMode:"CHOOSE"|"LOST";onClose:()=>void;onChanged:(value:OutcomeChanged)=>void}){
  const [mode,setMode]=useState<"CHOOSE"|"LOST">(initialMode),[reason,setReason]=useState<LostReason|"">(consultation.lostReason??""),[note,setNote]=useState(consultation.lostReasonNote??""),[pending,setPending]=useState(false),[error,setError]=useState("");
  const save=async(outcome:"CONTRACTED"|"LOST")=>{if(outcome==="CONTRACTED"&&!window.confirm(`${consultation.customerName} 고객님의 계약을 확정할까요?`))return;if(outcome==="LOST"&&!reason){setError("불성사 사유를 선택해주세요.");return}if(outcome==="LOST"&&reason==="OTHER"&&!note.trim()){setError("기타 사유를 입력해주세요.");return}setPending(true);setError("");const response=await fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/contract-outcome`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({outcome,lostReason:outcome==="LOST"?reason:null,lostReasonNote:outcome==="LOST"?note.trim()||null:null,idempotencyKey:crypto.randomUUID()})});setPending(false);if(!response.ok){setError("계약 결과를 저장하지 못했습니다.");return}onChanged({outcome,lostReason:outcome==="LOST"?reason as LostReason:null,lostReasonNote:outcome==="LOST"?note.trim()||null:null,decidedAt:new Date().toISOString(),status:outcome==="CONTRACTED"?"계약":"완료"});onClose()};
  return <div className="quote-drawer-layer" role="dialog" aria-modal="true" aria-labelledby="outcome-title"><button className="quote-drawer-backdrop" type="button" aria-label="계약 결과 닫기" onClick={onClose}/><aside className="quote-drawer outcome-drawer"><header><div><p>CONTRACT OUTCOME</p><h2 id="outcome-title">계약 결과 {consultation.contractOutcome==="PENDING"?"처리":"변경"}</h2></div><button type="button" aria-label="닫기" onClick={onClose}><X/></button></header><div className="outcome-customer"><strong>{consultation.customerName} 고객님</strong><span>{consultation.assignedUserName??"담당자 미지정"}</span></div>{mode==="CHOOSE"&&<section className="outcome-choice"><h3>변경할 결과를 선택해주세요.</h3><button type="button" disabled={pending} onClick={()=>void save("CONTRACTED")}>계약</button><button type="button" disabled={pending} onClick={()=>setMode("LOST")}>불성사</button></section>}{mode==="LOST"&&<section className="lost-fields"><label>불성사 사유 <strong>필수</strong><select value={reason} onChange={(event)=>setReason(event.target.value as LostReason|"")}><option value="">선택해주세요</option>{Object.entries(lostReasonLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>추가 메모 {reason==="OTHER"?<strong>필수</strong>:<small>선택</small>}<textarea value={note} maxLength={2000} onChange={(event)=>setNote(event.target.value)} placeholder="불성사 관련 내용을 입력해주세요."/></label><div><button type="button" disabled={pending} onClick={()=>setMode("CHOOSE")}>이전</button><button type="button" disabled={pending} onClick={()=>void save("LOST")}>{pending?"저장 중…":"불성사 확정"}</button></div></section>}{error&&<p className="quote-message" role="alert">{error}</p>}</aside></div>;
}
