"use client";

import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { ExternalLink,RefreshCw,X } from "lucide-react";
import { MAX_BATCH_SIZE,MAX_FILES,validateUploadFile } from "@/lib/consultations/file-policy";
import type { ConsultationFileCategory,UploadFileCategory } from "@/lib/consultations/consultation-file-repository";
import { formatConsultationRegion } from "@/lib/consultations/region-display";

type Choice={id:string;label:string;customerName:string;region:string;area:string};
type Customer={customerName:string;region:string;area:string};
type Item={id:string;fileCategory:ConsultationFileCategory;originalFileName:string;mimeType:string;fileSize:number;createdAt:string;driveFileId:string};
type FilesResponse={files?:Array<Item&{category?:ConsultationFileCategory;fileName?:string}>;reconciliation?:"not_requested"|"ok"|"drive_connection_unavailable"|"drive_folder_unavailable"|"drive_error";discovered?:number};
const imageSections:[UploadFileCategory,string][]=[["FIELD_PHOTO","현장사진"],["BEFORE","Before"],["AFTER","After"]];
const size=(value:number)=>value>=1024*1024?`${(value/1024/1024).toFixed(1)}MB`:`${Math.max(1,Math.round(value/1024))}KB`;

export function FileManagementPage({mode,choices,consultationId,selectedCustomer,initialFiles}:{mode:"images"|"documents";choices:Choice[];consultationId:string|null;selectedCustomer:Customer|null;initialFiles:Item[]}){
  const router=useRouter(),input=useRef<HTMLInputElement>(null),pendingCategory=useRef<UploadFileCategory>(mode==="images"?"FIELD_PHOTO":"DOCUMENT");
  const [files,setFiles]=useState(initialFiles),[status,setStatus]=useState(""),[loading,setLoading]=useState(false),[loadError,setLoadError]=useState<""|"files"|"drive">(""),[missing,setMissing]=useState<Set<string>>(new Set()),[preview,setPreview]=useState<Item|null>(null);

  const applyResult=(result:FilesResponse)=>{
    if(result.files)setFiles(result.files);
    if(result.reconciliation==="drive_connection_unavailable"||result.reconciliation==="drive_folder_unavailable"||result.reconciliation==="drive_error")setLoadError("drive");else setLoadError("");
    if(result.discovered)setStatus(`Drive에서 누락된 파일 ${result.discovered}개를 복구했습니다.`);
  };
  useEffect(()=>{
    if(!consultationId)return;let active=true;
    fetch(`/api/consultations/${encodeURIComponent(consultationId)}/files?reconcile=1`,{cache:"no-store"}).then(async(response)=>{if(!response.ok)throw new Error();const result=await response.json() as FilesResponse;if(active)applyResult(result);}).catch(()=>{if(active)setLoadError("files")});
    return()=>{active=false};
  },[consultationId]);

  const refresh=async()=>{if(!consultationId)return;setLoading(true);setStatus("");try{const response=await fetch(`/api/consultations/${encodeURIComponent(consultationId)}/files?reconcile=1`,{cache:"no-store"});if(!response.ok)throw new Error();applyResult(await response.json() as FilesResponse);}catch{setLoadError("files");}finally{setLoading(false)}};
  const choose=(category:UploadFileCategory)=>{pendingCategory.current=category;input.current?.click()};
  const upload=async(list:FileList|null)=>{if(!consultationId||!list)return;const selected=Array.from(list);if(!selected.length)return;if(selected.length>MAX_FILES||selected.reduce((sum,file)=>sum+file.size,0)>MAX_BATCH_SIZE){setStatus("한 번에 5개, 총 20MB까지 업로드할 수 있습니다.");return}for(const file of selected){const error=validateUploadFile(file,pendingCategory.current);if(error){setStatus(error);return}}setStatus("업로드 중…");const form=new FormData();form.set("category",pendingCategory.current);form.set("idempotencyKey",crypto.randomUUID());selected.forEach(file=>form.append("files",file));try{const response=await fetch(`/api/consultations/${encodeURIComponent(consultationId)}/files`,{method:"POST",body:form});const result=await response.json() as FilesResponse;if(!response.ok)throw new Error();if(result.files)setFiles(result.files);setLoadError("");setStatus("업로드 완료")}catch{setStatus("업로드 실패")}finally{if(input.current)input.current.value=""}};
  const selector=<label className="customer-selector"><span>고객 선택</span><select value={consultationId??""} onChange={event=>{setStatus("고객 자료를 불러오는 중…");router.push(`/${mode}?consultation=${encodeURIComponent(event.target.value)}`)}}><option value="" disabled>상담 고객을 선택해주세요</option>{choices.map(choice=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</select></label>;
  if(!consultationId)return <div className="files-page"><header><p>DRIVE FILES</p><h1>{mode==="images"?"이미지":"서류"}</h1></header>{selector}<div className="files-empty">아직 선택할 상담이 없습니다.</div></div>;
  const inputNode=<input hidden ref={input} type="file" multiple accept={mode==="images"?".jpg,.jpeg,.png,.webp,.heic,.heif":".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.hwp"} onChange={event=>void upload(event.target.files)}/>;
  const errorNode=loadError==="files"?<p className="file-load-error" role="alert">{mode==="images"?"이미지를":"서류를"} 불러오지 못했습니다. <button onClick={()=>void refresh()}>다시 시도</button></p>:loadError==="drive"?<p className="file-load-error file-drive-error" role="alert">Google Drive 연결을 확인해주세요. 기존에 동기화된 파일만 표시됩니다.</p>:null;
  return <div className="files-page"><header className="files-title"><div><p>DRIVE FILES</p><h1>{mode==="images"?"이미지":"서류"}</h1></div><button className="drive-refresh" type="button" disabled={loading} onClick={()=>void refresh()}><RefreshCw/>{loading?"확인 중…":"Drive 파일 새로고침"}</button></header>{selector}{selectedCustomer&&<div className="selected-customer"><span>고객</span><strong>{selectedCustomer.customerName} · {formatConsultationRegion(selectedCustomer.region)} · {selectedCustomer.area}</strong></div>}{inputNode}{status&&<p className="file-upload-status" role="status">{status}</p>}{errorNode}{mode==="images"?imageSections.map(([category,label])=>{const items=files.filter(file=>file.fileCategory===category);return <section className="managed-section" key={category}><header><h2>{label}</h2><div><button onClick={()=>choose(category)}>사진 추가</button><a target="_blank" rel="noreferrer" href={`/api/consultations/${encodeURIComponent(consultationId)}/folders/${category}/open`}>폴더 열기</a></div></header>{items.length?<div className="image-grid">{items.map(file=><button type="button" onClick={()=>setPreview(file)} key={file.id}>{missing.has(file.id)?<span className="missing-preview">Drive에서 파일을 찾을 수 없습니다.</span>:<Image unoptimized width={320} height={240} src={`/api/consultations/${encodeURIComponent(consultationId)}/files/${encodeURIComponent(file.id)}/preview`} alt={file.originalFileName} onError={()=>setMissing(current=>new Set(current).add(file.id))}/>}<strong>{file.originalFileName}</strong><small>{size(file.fileSize)} · {new Date(file.createdAt).toLocaleDateString("ko-KR")}</small></button>)}</div>:<p className="files-empty">등록된 이미지가 없습니다.</p>}</section>})
  :<><section className="managed-section original-document"><header><h2>상담 원본</h2></header>{files.filter(file=>file.fileCategory==="CHECKLIST_ORIGINAL").map(file=><FileRow key={file.id} file={file} consultationId={consultationId} original/>)}{!files.some(file=>file.fileCategory==="CHECKLIST_ORIGINAL")&&<p className="files-empty">원본 PDF 동기화가 필요합니다.</p>}</section><section className="managed-section"><header><h2>업로드한 서류</h2><div><button onClick={()=>choose("DOCUMENT")}>서류 추가</button><a target="_blank" rel="noreferrer" href={`/api/consultations/${encodeURIComponent(consultationId)}/folders/DOCUMENT/open`}>폴더 열기</a></div></header>{files.filter(file=>file.fileCategory==="DOCUMENT").map(file=><FileRow key={file.id} file={file} consultationId={consultationId}/>)}{!files.some(file=>file.fileCategory==="DOCUMENT")&&<p className="files-empty">등록된 서류가 없습니다.</p>}</section></>}
    {preview&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label={`${preview.originalFileName} 미리보기`}><button className="image-lightbox-backdrop" type="button" aria-label="미리보기 닫기" onClick={()=>setPreview(null)}/><div><header><strong>{preview.originalFileName}</strong><button type="button" aria-label="닫기" onClick={()=>setPreview(null)}><X/></button></header><Image unoptimized width={1400} height={1000} src={`/api/consultations/${encodeURIComponent(consultationId)}/files/${encodeURIComponent(preview.id)}/preview`} alt={preview.originalFileName}/><footer><span>{size(preview.fileSize)}</span><a target="_blank" rel="noreferrer" href={`/api/consultations/${encodeURIComponent(consultationId)}/files/${encodeURIComponent(preview.id)}/open`}>Drive에서 열기 <ExternalLink/></a></footer></div></div>}
  </div>;
}

function FileRow({file,consultationId,original=false}:{file:Item;consultationId:string;original?:boolean}){const extension=file.originalFileName.split(".").pop()?.toUpperCase()??"FILE";return <div className="managed-file-row"><div><strong>{original?"상담 체크리스트 원본":file.originalFileName}</strong>{original&&<span>{file.originalFileName}</span>}<small>{extension} · {size(file.fileSize)} · {new Date(file.createdAt).toLocaleDateString("ko-KR")}</small></div><a target="_blank" rel="noreferrer" href={`/api/consultations/${encodeURIComponent(consultationId)}/files/${encodeURIComponent(file.id)}/open`}>{original?"원본 PDF 열기":"열기"}</a></div>}
