"use client";
import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { MAX_BATCH_SIZE,MAX_FILES,validateUploadFile } from "@/lib/consultations/file-policy";
import type { ConsultationFileCategory,UploadFileCategory } from "@/lib/consultations/consultation-file-repository";
type Choice={id:string;label:string};type Item={id:string;fileCategory:ConsultationFileCategory;originalFileName:string;fileSize:number;createdAt:string};
const imageSections:[UploadFileCategory,string][]=[["FIELD_PHOTO","현장사진"],["BEFORE","Before"],["AFTER","After"]];
const size=(value:number)=>value>=1024*1024?`${(value/1024/1024).toFixed(1)}MB`:`${Math.max(1,Math.round(value/1024))}KB`;
export function FileManagementPage({mode,choices,consultationId,initialFiles}:{mode:"images"|"documents";choices:Choice[];consultationId:string|null;initialFiles:Item[]}){const router=useRouter(),input=useRef<HTMLInputElement>(null),pendingCategory=useRef<UploadFileCategory>(mode==="images"?"FIELD_PHOTO":"DOCUMENT"),[files,setFiles]=useState(initialFiles),[status,setStatus]=useState("");
 const [missing,setMissing]=useState<Set<string>>(new Set());
 const choose=(category:UploadFileCategory)=>{pendingCategory.current=category;input.current?.click();};
 const upload=async(list:FileList|null)=>{if(!consultationId||!list)return;const selected=Array.from(list);if(!selected.length)return;if(selected.length>MAX_FILES||selected.reduce((sum,file)=>sum+file.size,0)>MAX_BATCH_SIZE){setStatus("한 번에 5개, 총 20MB까지 업로드할 수 있습니다.");return;}for(const file of selected){const error=validateUploadFile(file,pendingCategory.current);if(error){setStatus(error);return;}}setStatus("업로드 중…");const form=new FormData();form.set("category",pendingCategory.current);form.set("idempotencyKey",crypto.randomUUID());selected.forEach(file=>form.append("files",file));try{const response=await fetch(`/api/consultations/${consultationId}/files`,{method:"POST",body:form});const result=await response.json() as {files?:Item[]};if(!response.ok)throw new Error();setFiles(result.files??files);setStatus("업로드 완료");}catch{setStatus("업로드 실패");}finally{if(input.current)input.current.value="";}};
 const selector=<label className="customer-selector"><span>고객 선택</span><select value={consultationId??""} onChange={event=>router.push(`/${mode}?consultation=${encodeURIComponent(event.target.value)}`)}><option value="" disabled>상담 고객을 선택해주세요</option>{choices.map(choice=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</select></label>;
 if(!consultationId)return <div className="files-page"><header><p>DRIVE FILES</p><h1>{mode==="images"?"이미지":"서류"}</h1></header>{selector}<div className="files-empty">아직 선택할 상담이 없습니다.</div></div>;
 const inputNode=<input hidden ref={input} type="file" multiple accept={mode==="images"?".jpg,.jpeg,.png,.webp,.heic,.heif":".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.hwp"} onChange={event=>void upload(event.target.files)}/>;
 return <div className="files-page"><header><p>DRIVE FILES</p><h1>{mode==="images"?"이미지":"서류"}</h1></header>{selector}{inputNode}{status&&<p className="file-upload-status" role="status">{status}</p>}{mode==="images"?imageSections.map(([category,label])=>{const items=files.filter(file=>file.fileCategory===category);return <section className="managed-section" key={category}><header><h2>{label}</h2><div><button onClick={()=>choose(category)}>사진 추가</button><a target="_blank" href={`/api/consultations/${consultationId}/folders/${category}/open`}>폴더 열기</a></div></header>{items.length?<div className="image-grid">{items.map(file=><a target="_blank" href={`/api/consultations/${consultationId}/files/${file.id}/open`} key={file.id}>{missing.has(file.id)?<span className="missing-preview">Drive에서 파일을 찾을 수 없습니다.</span>:<Image unoptimized width={320} height={240} src={`/api/consultations/${consultationId}/files/${file.id}/preview`} alt={file.originalFileName} onError={()=>setMissing(current=>new Set(current).add(file.id))}/>}<strong>{file.originalFileName}</strong></a>)}</div>:<p className="files-empty">등록된 이미지가 없습니다.</p>}</section>;})
 :<><section className="managed-section original-document"><header><h2>상담 원본</h2></header>{files.filter(file=>file.fileCategory==="CHECKLIST_ORIGINAL").map(file=><FileRow key={file.id} file={file} consultationId={consultationId} original/>)}{!files.some(file=>file.fileCategory==="CHECKLIST_ORIGINAL")&&<p className="files-empty">원본 PDF 동기화가 필요합니다.</p>}</section><section className="managed-section"><header><h2>업로드한 서류</h2><div><button onClick={()=>choose("DOCUMENT")}>서류 추가</button><a target="_blank" href={`/api/consultations/${consultationId}/folders/DOCUMENT/open`}>폴더 열기</a></div></header>{files.filter(file=>file.fileCategory==="DOCUMENT").map(file=><FileRow key={file.id} file={file} consultationId={consultationId}/>)}{!files.some(file=>file.fileCategory==="DOCUMENT")&&<p className="files-empty">등록된 서류가 없습니다.</p>}</section></>}</div>;
}
function FileRow({file,consultationId,original=false}:{file:Item;consultationId:string;original?:boolean}){const extension=file.originalFileName.split(".").pop()?.toUpperCase()??"FILE";return <div className="managed-file-row"><div><strong>{original?"상담 체크리스트 원본":file.originalFileName}</strong>{original&&<span>{file.originalFileName}</span>}<small>{extension} · {size(file.fileSize)} · {new Date(file.createdAt).toLocaleDateString("ko-KR")}</small></div><a target="_blank" href={`/api/consultations/${consultationId}/files/${file.id}/open`}>{original?"원본 PDF 열기":"열기"}</a></div>;}
