"use client";

import { useMemo,useState } from "react";
import Link from "next/link";
import type { Consultation,ContractOutcome } from "@/types/consultation";
import { QuoteEditor } from "./quote-editor";
import { ContractOutcomeEditor,type OutcomeChanged } from "./contract-outcome-editor";
import { formatManWon,quoteStatusLabel } from "@/lib/consultations/quote-display";
import { formatConsultationRegion } from "@/lib/consultations/region-display";
import { formatSeoulDateTime } from "@/lib/consultations/reservation-time";

const columns:[ContractOutcome,string][]=[["PENDING","결정 대기"],["CONTRACTED","계약"],["LOST","불성사"]];
export function QuotesPage({consultations,members,currentUserId,initialConsultationId}:{consultations:Consultation[];members:{userId:string;name:string}[];currentUserId:string;initialConsultationId?:string}){
  const [items,setItems]=useState(consultations),[assigneeFilter,setAssigneeFilter]=useState("ALL"),[quoteTargetId,setQuoteTargetId]=useState<string|null>(consultations.find((item)=>item.id===initialConsultationId)?.id??null),[outcomeTarget,setOutcomeTarget]=useState<{id:string;mode:"CHOOSE"|"LOST"}|null>(null),[confirmTargetId,setConfirmTargetId]=useState<string|null>(null),[draggingId,setDraggingId]=useState<string|null>(null),[dropColumn,setDropColumn]=useState<ContractOutcome|null>(null),[pendingId,setPendingId]=useState<string|null>(null),[error,setError]=useState("");
  const filtered=useMemo(()=>items.filter((item)=>assigneeFilter==="ALL"||assigneeFilter==="ME"&&item.assignedUserId===currentUserId||assigneeFilter==="UNASSIGNED"&&!item.assignedUserId||item.assignedUserId===assigneeFilter),[items,assigneeFilter,currentUserId]);
  const applyOutcome=(id:string,value:OutcomeChanged)=>setItems((current)=>current.map((item)=>item.id===id?{...item,contractOutcome:value.outcome,contractDecidedAt:value.decidedAt,lostReason:value.lostReason,lostReasonNote:value.lostReasonNote,status:value.status}:item));
  const contract=async(item:Consultation)=>{setPendingId(item.id);setError("");try{const response=await fetch(`/api/consultations/${encodeURIComponent(item.id)}/contract-outcome`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({outcome:"CONTRACTED",lostReason:null,lostReasonNote:null,idempotencyKey:crypto.randomUUID()})});if(!response.ok){setError("계약 결과를 저장하지 못했습니다.");return}applyOutcome(item.id,{outcome:"CONTRACTED",lostReason:null,lostReasonNote:null,decidedAt:new Date().toISOString(),status:"계약"});setConfirmTargetId(null)}catch{setError("계약 결과를 저장하지 못했습니다.")}finally{setPendingId(null)}};
  const drop=(outcome:ContractOutcome,id:string|null)=>{setDropColumn(null);const item=items.find((value)=>value.id===(id||draggingId));setDraggingId(null);if(!item||item.contractOutcome===outcome||outcome==="PENDING"||item.quoteStatus!=="SENT")return;if(outcome==="CONTRACTED")setConfirmTargetId(item.id);else setOutcomeTarget({id:item.id,mode:"LOST"})};
  const quoteTarget=quoteTargetId?items.find((item)=>item.id===quoteTargetId)??null:null,outcomeItem=outcomeTarget?items.find((item)=>item.id===outcomeTarget.id)??null:null,confirmItem=confirmTargetId?items.find((item)=>item.id===confirmTargetId)??null:null;
  return <main className="quotes-page quotes-kanban-page"><header><div><p>QUOTES</p><h1>견적</h1><span>견적 카드를 이동해 계약 결과를 관리하세요.</span></div><label>담당자<select value={assigneeFilter} onChange={(event)=>setAssigneeFilter(event.target.value)}><option value="ALL">전체 담당자</option><option value="ME">내 상담</option><option value="UNASSIGNED">미지정</option>{members.map((member)=><option value={member.userId} key={member.userId}>{member.name}</option>)}</select></label></header>{error&&<p className="quotes-action-error" role="alert">{error}</p>}<section className="quote-kanban">{columns.map(([outcome,label])=>{const columnItems=filtered.filter((item)=>item.contractOutcome===outcome);return <section className={`quote-kanban-column${dropColumn===outcome?" is-drop-target":""}`} key={outcome} onDragOver={(event)=>{event.preventDefault();setDropColumn(outcome)}} onDragLeave={(event)=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setDropColumn(null)}} onDrop={(event)=>{event.preventDefault();drop(outcome,event.dataTransfer.getData("text/plain")||null)}}><header><h2>{label}</h2><span>{columnItems.length}</span></header><div>{columnItems.map((item)=><article className={`quote-kanban-card${item.quoteStatus==="SENT"?" is-draggable":""}`} draggable={item.quoteStatus==="SENT"} onDragStart={(event)=>{setDraggingId(item.id);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",item.id)}} onDragEnd={()=>{setDraggingId(null);setDropColumn(null)}} key={item.id}><button type="button" onClick={()=>setQuoteTargetId(item.id)}><strong>{item.customerName}</strong><span>{formatConsultationRegion(item.region)}</span><b>{formatManWon(item.quoteAmount)}</b><small>담당 {item.assignedUserName??"미지정"}</small><time>{item.quoteSentAt?formatSeoulDateTime(item.quoteSentAt):quoteStatusLabel[item.quoteStatus]}</time></button><Link href={`/consultations/${encodeURIComponent(item.id)}`}>상담 보기</Link></article>)}{!columnItems.length&&<p>카드를 이곳에 놓으세요.</p>}</div></section>})}</section>{quoteTarget&&<QuoteEditor consultation={quoteTarget} open showTrigger={false} onOpenChange={(open)=>{if(!open)setQuoteTargetId(null)}}/>}{outcomeTarget&&outcomeItem&&<ContractOutcomeEditor consultation={outcomeItem} initialMode={outcomeTarget.mode} onClose={()=>setOutcomeTarget(null)} onChanged={(value)=>applyOutcome(outcomeItem.id,value)}/>} {confirmItem&&<div className="contract-confirm-layer" role="dialog" aria-modal="true" aria-labelledby="contract-confirm-title"><button className="contract-confirm-backdrop" type="button" aria-label="취소" onClick={()=>setConfirmTargetId(null)}/><section><h2 id="contract-confirm-title">계약 확정</h2><p>{confirmItem.customerName} 고객을 계약으로 처리하시겠습니까?</p><div><button type="button" disabled={pendingId===confirmItem.id} onClick={()=>setConfirmTargetId(null)}>취소</button><button type="button" disabled={pendingId===confirmItem.id} onClick={()=>void contract(confirmItem)}>{pendingId===confirmItem.id?"처리 중…":"계약 확정"}</button></div></section></div>}</main>;
}
