"use client";

import { useEffect,useState } from "react";
import { FileText,X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { Consultation,LostReason } from "@/types/consultation";
import { formatConsultationRegion } from "@/lib/consultations/region-display";
import { lostReasonLabel } from "@/lib/consultations/quote-display";

type DocumentFile={id:string;fileCategory:string;originalFileName:string};
export function QuoteEditor({consultation,open,onOpenChange,showTrigger=true}:{consultation:Consultation;open?:boolean;onOpenChange?:(open:boolean)=>void;showTrigger?:boolean}){
  const router=useRouter(),[internalOpen,setInternalOpen]=useState(false),visible=open??internalOpen;const setOpen=(next:boolean)=>{setInternalOpen(next);onOpenChange?.(next)};
  const [amount,setAmount]=useState(consultation.quoteAmount?.toLocaleString("ko-KR")??""),[note,setNote]=useState(consultation.quoteNote??""),[fileId,setFileId]=useState(consultation.quoteFileId??""),[files,setFiles]=useState<DocumentFile[]>([]),[pending,setPending]=useState(false),[message,setMessage]=useState("");
  const [lostOpen,setLostOpen]=useState(false),[lostReason,setLostReason]=useState<LostReason|"">(consultation.lostReason??""),[lostNote,setLostNote]=useState(consultation.lostReasonNote??"");
  useEffect(()=>{if(!visible)return;void fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/files`).then(async(response)=>response.ok?await response.json() as {files?:DocumentFile[]}:{files:[]}).then((result)=>setFiles((result.files??[]).filter((file)=>file.fileCategory==="DOCUMENT")))},[visible,consultation.id]);
  const numericAmount=Number(amount.replace(/\D/g,""));
  const save=async(action:"SAVE"|"SEND")=>{if(!Number.isSafeInteger(numericAmount)||numericAmount<=0){setMessage("견적 금액을 입력해주세요.");return}setPending(true);setMessage("");const response=await fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/quote`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({amount:numericAmount,note:note.trim()||null,fileId:fileId||null,action,idempotencyKey:crypto.randomUUID()})});setPending(false);if(!response.ok){const result=await response.json().catch(()=>({})) as {error?:string};setMessage(result.error==="consultation_not_completed"?"상담 완료 후 견적을 등록할 수 있습니다.":"견적을 저장하지 못했습니다.");return}setOpen(false);router.refresh()};
  const outcome=async(value:"CONTRACTED"|"LOST")=>{if(value==="LOST"&&!lostReason){setMessage("불성사 사유를 선택해주세요.");return}if(value==="LOST"&&lostReason==="OTHER"&&!lostNote.trim()){setMessage("기타 사유를 입력해주세요.");return}setPending(true);setMessage("");const response=await fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/contract-outcome`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({outcome:value,lostReason:value==="LOST"?lostReason:null,lostReasonNote:value==="LOST"?lostNote.trim()||null:null,idempotencyKey:crypto.randomUUID()})});setPending(false);if(!response.ok){setMessage("계약 결과를 저장하지 못했습니다.");return}setLostOpen(false);setOpen(false);router.refresh()};
  return <>{showTrigger&&<button className="quote-trigger" type="button" onClick={()=>setOpen(true)}>{consultation.quoteStatus==="NOT_CREATED"?"견적 등록":"견적 수정"}</button>}{visible&&<div className="quote-drawer-layer" role="dialog" aria-modal="true" aria-labelledby="quote-title"><button className="quote-drawer-backdrop" type="button" aria-label="견적 닫기" onClick={()=>setOpen(false)}/><aside className="quote-drawer"><header><div><p>QUOTE</p><h2 id="quote-title">견적 {consultation.quoteStatus==="NOT_CREATED"?"등록":"수정"}</h2></div><button type="button" aria-label="닫기" onClick={()=>setOpen(false)}><X/></button></header><dl className="quote-customer"><div><dt>고객명</dt><dd>{consultation.customerName}</dd></div><div><dt>지역</dt><dd>{formatConsultationRegion(consultation.region)}</dd></div><div><dt>담당자</dt><dd>{consultation.assignedUserName??"미지정"}</dd></div></dl><div className="quote-fields"><label>견적 금액<input inputMode="numeric" value={amount} placeholder="45,000,000" onChange={(event)=>setAmount(event.target.value.replace(/\D/g,"").replace(/^0+(?=\d)/,"").replace(/\B(?=(\d{3})+(?!\d))/g,","))}/></label><label>견적 메모 <small>선택</small><textarea value={note} maxLength={2000} onChange={(event)=>setNote(event.target.value)}/></label><label>견적서 파일 <small>기존 서류</small><select value={fileId} onChange={(event)=>setFileId(event.target.value)}><option value="">연결 안 함</option>{files.map((file)=><option key={file.id} value={file.id}>{file.originalFileName}</option>)}</select></label>{!files.length&&<a href={`/documents?consultation=${encodeURIComponent(consultation.id)}`}>서류에서 견적서 업로드하기</a>}</div><div className="quote-save-actions"><button type="button" disabled={pending} onClick={()=>void save("SAVE")}>{consultation.quoteStatus==="SENT"?"변경 저장":"임시 저장"}</button><button type="button" disabled={pending} onClick={()=>void save("SEND")}>견적 발송 처리</button></div>{consultation.quoteStatus==="SENT"&&<section className="outcome-actions"><h3>계약 결과</h3><div><button type="button" disabled={pending} onClick={()=>void outcome("CONTRACTED")}>계약</button><button type="button" disabled={pending} onClick={()=>setLostOpen((value)=>!value)}>불성사</button></div>{lostOpen&&<div className="lost-fields"><label>불성사 사유<select value={lostReason} onChange={(event)=>setLostReason(event.target.value as LostReason|"")}><option value="">선택해주세요</option>{Object.entries(lostReasonLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>메모 {lostReason==="OTHER"?"(필수)":"(선택)"}<textarea value={lostNote} maxLength={2000} onChange={(event)=>setLostNote(event.target.value)}/></label><button type="button" disabled={pending} onClick={()=>void outcome("LOST")}>불성사 저장</button></div>}</section>}{fileId&&<p className="quote-file"><FileText/>선택한 견적서가 상담 서류와 연결됩니다.</p>}{message&&<p className="quote-message" role="status">{message}</p>}</aside></div>}</>;
}
