"use client";

import { useEffect,useRef,useState } from "react";
import { ExternalLink,FileUp,X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { Consultation } from "@/types/consultation";
import { formatConsultationRegion } from "@/lib/consultations/region-display";
import { validateUploadFile } from "@/lib/consultations/file-policy";

type DocumentFile={id:string;fileCategory:string;originalFileName:string;mimeType?:string;fileSize?:number};
export function QuoteEditor({consultation,open,onOpenChange,showTrigger=true}:{consultation:Consultation;open?:boolean;onOpenChange?:(open:boolean)=>void;showTrigger?:boolean}){
  const router=useRouter(),input=useRef<HTMLInputElement>(null),[internalOpen,setInternalOpen]=useState(false),visible=open??internalOpen;const setOpen=(next:boolean)=>{setInternalOpen(next);onOpenChange?.(next)};
  const [amount,setAmount]=useState(consultation.quoteAmount?Math.round(consultation.quoteAmount/10000).toLocaleString("ko-KR"):""),[note,setNote]=useState(consultation.quoteNote??""),[fileId,setFileId]=useState(consultation.quoteFileId??""),[files,setFiles]=useState<DocumentFile[]>([]),[pending,setPending]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{if(!visible)return;void fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/files`).then(async(response)=>response.ok?await response.json() as {files?:DocumentFile[]}:{files:[]}).then((result)=>setFiles((result.files??[]).filter((file)=>file.fileCategory==="DOCUMENT")))},[visible,consultation.id]);
  const amountInManWon=Number(amount.replace(/\D/g,"")),actualAmount=amountInManWon*10000,selectedFile=files.find((file)=>file.id===fileId)??null;
  const upload=async(file:File|undefined)=>{if(!file)return;const validation=validateUploadFile(file,"DOCUMENT");if(validation){setMessage(validation);return}setUploading(true);setMessage("");const form=new FormData();form.set("category","DOCUMENT");form.set("idempotencyKey",crypto.randomUUID());form.append("files",file);const response=await fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/files`,{method:"POST",body:form});const result=await response.json().catch(()=>null) as {files?:DocumentFile[]}|null;setUploading(false);if(input.current)input.current.value="";if(!response.ok||!result?.files){setMessage("파일을 업로드하지 못했습니다.");return}const documents=result.files.filter((item)=>item.fileCategory==="DOCUMENT");setFiles(documents);const uploaded=documents.find((item)=>item.originalFileName===file.name)??documents[0];if(uploaded)setFileId(uploaded.id)};
  const save=async(action:"SAVE"|"SEND")=>{if(!Number.isSafeInteger(amountInManWon)||amountInManWon<=0||!Number.isSafeInteger(actualAmount)){setMessage("견적 금액을 입력해주세요.");return}setPending(true);setMessage("");const response=await fetch(`/api/consultations/${encodeURIComponent(consultation.id)}/quote`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({amount:actualAmount,note:note.trim()||null,fileId:fileId||null,action,idempotencyKey:crypto.randomUUID()})});setPending(false);if(!response.ok){const result=await response.json().catch(()=>({})) as {error?:string};setMessage(result.error==="consultation_not_completed"?"상담 완료 후 견적을 등록할 수 있습니다.":"견적을 저장하지 못했습니다.");return}setOpen(false);router.refresh()};
  return <>{showTrigger&&<button className="quote-trigger" type="button" onClick={()=>setOpen(true)}>{consultation.quoteStatus==="NOT_CREATED"?"견적 등록":"견적 수정"}</button>}{visible&&<div className="quote-drawer-layer" role="dialog" aria-modal="true" aria-labelledby="quote-title"><button className="quote-drawer-backdrop" type="button" aria-label="견적 닫기" onClick={()=>setOpen(false)}/><aside className="quote-drawer"><header><div><p>QUOTE</p><h2 id="quote-title">견적 {consultation.quoteStatus==="NOT_CREATED"?"등록":"수정"}</h2></div><button type="button" aria-label="닫기" onClick={()=>setOpen(false)}><X/></button></header><dl className="quote-customer"><div><dt>고객명</dt><dd>{consultation.customerName}</dd></div><div><dt>지역</dt><dd>{formatConsultationRegion(consultation.region)}</dd></div><div><dt>담당자</dt><dd>{consultation.assignedUserName??"미지정"}</dd></div></dl><div className="quote-fields"><label>견적 금액<div className="quote-amount-input"><input inputMode="numeric" value={amount} placeholder="4,500" onChange={(event)=>setAmount(event.target.value.replace(/\D/g,"").replace(/^0+(?=\d)/,"").replace(/\B(?=(\d{3})+(?!\d))/g,","))}/><span>만원</span></div></label><div className="quote-upload-field"><strong>견적서 파일</strong><input hidden ref={input} type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.hwp" onChange={(event)=>void upload(event.target.files?.[0])}/>{selectedFile?<div className="quote-uploaded-file"><span>{selectedFile.originalFileName}</span><div><a target="_blank" rel="noreferrer" href={`/api/consultations/${encodeURIComponent(consultation.id)}/files/${encodeURIComponent(selectedFile.id)}/open`}>열기 <ExternalLink/></a><button type="button" disabled={uploading} onClick={()=>input.current?.click()}>변경</button></div></div>:<button className="quote-upload-button" type="button" disabled={uploading} onClick={()=>input.current?.click()}><FileUp/>{uploading?"업로드 중…":"파일 업로드"}</button>}</div><label>견적 메모 <small>선택</small><textarea value={note} maxLength={2000} onChange={(event)=>setNote(event.target.value)}/></label></div><div className="quote-save-actions"><button type="button" disabled={pending||uploading} onClick={()=>void save("SAVE")}>{consultation.quoteStatus==="SENT"?"변경 저장":"임시 저장"}</button><button type="button" disabled={pending||uploading} onClick={()=>void save("SEND")}>견적 발송 처리</button></div>{message&&<p className="quote-message" role="status">{message}</p>}</aside></div>}</>;
}
