"use client";

import { useMemo,useState } from "react";
import Link from "next/link";
import type { Consultation,ContractOutcome } from "@/types/consultation";
import { QuoteEditor } from "./quote-editor";
import { contractOutcomeLabel,formatManWon,quoteStatusLabel } from "@/lib/consultations/quote-display";
import { formatConsultationRegion } from "@/lib/consultations/region-display";
import { formatSeoulDateTime } from "@/lib/consultations/reservation-time";

type ResultFilter="ALL"|ContractOutcome;
export function QuotesPage({consultations,members,currentUserId,initialConsultationId}:{consultations:Consultation[];members:{userId:string;name:string}[];currentUserId:string;initialConsultationId?:string}){
  const [resultFilter,setResultFilter]=useState<ResultFilter>("ALL"),[assigneeFilter,setAssigneeFilter]=useState("ALL"),[target,setTarget]=useState<Consultation|null>(consultations.find((item)=>item.id===initialConsultationId)??null);
  const filtered=useMemo(()=>consultations.filter((item)=>resultFilter==="ALL"||item.contractOutcome===resultFilter).filter((item)=>assigneeFilter==="ALL"||assigneeFilter==="ME"&&item.assignedUserId===currentUserId||assigneeFilter==="UNASSIGNED"&&!item.assignedUserId||item.assignedUserId===assigneeFilter),[consultations,resultFilter,assigneeFilter,currentUserId]);
  const counts={ALL:consultations.length,PENDING:consultations.filter((item)=>item.contractOutcome==="PENDING").length,CONTRACTED:consultations.filter((item)=>item.contractOutcome==="CONTRACTED").length,LOST:consultations.filter((item)=>item.contractOutcome==="LOST").length};
  return <main className="quotes-page"><header><div><p>QUOTES</p><h1>견적</h1><span>상담 완료 후 견적과 계약 결과를 관리하세요.</span></div><label>담당자<select value={assigneeFilter} onChange={(event)=>setAssigneeFilter(event.target.value)}><option value="ALL">전체 담당자</option><option value="ME">내 상담</option><option value="UNASSIGNED">미지정</option>{members.map((member)=><option value={member.userId} key={member.userId}>{member.name}</option>)}</select></label></header><nav className="quote-tabs" aria-label="계약 결과 필터">{(["ALL","PENDING","CONTRACTED","LOST"] as ResultFilter[]).map((value)=><button type="button" className={resultFilter===value?"is-active":""} onClick={()=>setResultFilter(value)} key={value}>{value==="ALL"?"전체":contractOutcomeLabel[value]} <small>{counts[value]}</small></button>)}</nav><section className="quotes-table-wrap"><table className="quotes-table"><thead><tr><th>고객명</th><th>현장</th><th>담당자</th><th>상담 완료일</th><th>견적</th><th>발송일</th><th>계약 결과</th><th>관리</th></tr></thead><tbody>{filtered.map((item)=><tr key={item.id}><td><strong>{item.customerName}</strong><small>{item.areaSize}</small></td><td>{formatConsultationRegion(item.region)}</td><td>{item.assignedUserName??"미지정"}</td><td>{item.statusUpdatedAt?formatSeoulDateTime(item.statusUpdatedAt):"-"}</td><td><strong>{formatManWon(item.quoteAmount)}</strong><small>{quoteStatusLabel[item.quoteStatus]}</small></td><td>{item.quoteSentAt?formatSeoulDateTime(item.quoteSentAt):"-"}</td><td><span className={`outcome-badge outcome-${item.contractOutcome.toLowerCase()}`}>{contractOutcomeLabel[item.contractOutcome]}</span></td><td><div><button type="button" onClick={()=>setTarget(item)}>{item.quoteStatus==="NOT_CREATED"?"견적 등록":"견적 수정"}</button><Link href={`/consultations/${encodeURIComponent(item.id)}`}>상담 보기</Link><Link href={`/documents?consultation=${encodeURIComponent(item.id)}`}>서류</Link></div></td></tr>)}</tbody></table>{!filtered.length&&<p className="quotes-empty">조건에 맞는 견적이 없습니다.</p>}</section>{target&&<QuoteEditor consultation={target} open showTrigger={false} onOpenChange={(open)=>{if(!open)setTarget(null)}}/>}</main>;
}
