import { getDb } from "@/lib/db/client";

export interface QuoteFollowupSummary{consultationId:string;nextContactAt:string|null;latestNote:string|null}
export interface QuoteFollowupNote{id:string;content:string;authorName:string;createdAt:string}
export async function getQuoteFollowupHistory(workspaceId:string,consultationId:string){const db=await getDb(),consultation=await db.prepare(`SELECT 1 FROM consultations WHERE id=? AND workspace_id=?`).bind(consultationId,workspaceId).first();if(!consultation)return null;const schedule=await db.prepare(`SELECT next_contact_at FROM quote_followup_schedules WHERE workspace_id=? AND consultation_id=?`).bind(workspaceId,consultationId).first<{next_contact_at:string}>(),notes=await db.prepare(`SELECT n.id,n.content,n.created_at,COALESCE(NULLIF(u.display_name,''),u.google_name,u.email,'알 수 없음') AS author_name FROM quote_followup_notes n LEFT JOIN users u ON u.id=n.author_user_id WHERE n.workspace_id=? AND n.consultation_id=? ORDER BY n.created_at DESC,n.id DESC LIMIT 100`).bind(workspaceId,consultationId).all<{id:string;content:string;created_at:string;author_name:string}>();return {nextContactAt:schedule?.next_contact_at??null,notes:notes.results.map((row)=>({id:row.id,content:row.content,createdAt:row.created_at,authorName:row.author_name}))}}
const eligible=async(workspaceId:string,consultationId:string)=>Boolean(await (await getDb()).prepare(`SELECT 1 AS found FROM consultations WHERE id=? AND workspace_id=? AND quote_status='SENT' AND contract_outcome='PENDING' LIMIT 1`).bind(consultationId,workspaceId).first());
export async function listQuoteFollowupSummaries(workspaceId:string){const result=await (await getDb()).prepare(`SELECT c.id AS consultation_id,s.next_contact_at,(SELECT n.content FROM quote_followup_notes n WHERE n.workspace_id=c.workspace_id AND n.consultation_id=c.id ORDER BY n.created_at DESC,n.id DESC LIMIT 1) AS latest_note FROM consultations c LEFT JOIN quote_followup_schedules s ON s.consultation_id=c.id AND s.workspace_id=c.workspace_id WHERE c.workspace_id=? AND c.quote_status='SENT' AND c.contract_outcome='PENDING'`).bind(workspaceId).all<{consultation_id:string;next_contact_at:string|null;latest_note:string|null}>();return result.results.map((row)=>({consultationId:row.consultation_id,nextContactAt:row.next_contact_at,latestNote:row.latest_note}))}
export async function getQuoteFollowup(workspaceId:string,consultationId:string){if(!await eligible(workspaceId,consultationId))return null;const db=await getDb(),schedule=await db.prepare(`SELECT next_contact_at FROM quote_followup_schedules WHERE workspace_id=? AND consultation_id=?`).bind(workspaceId,consultationId).first<{next_contact_at:string}>(),notes=await db.prepare(`SELECT n.id,n.content,n.created_at,COALESCE(NULLIF(u.display_name,''),u.google_name,u.email,'알 수 없음') AS author_name FROM quote_followup_notes n LEFT JOIN users u ON u.id=n.author_user_id WHERE n.workspace_id=? AND n.consultation_id=? ORDER BY n.created_at DESC,n.id DESC LIMIT 100`).bind(workspaceId,consultationId).all<{id:string;content:string;created_at:string;author_name:string}>();return {nextContactAt:schedule?.next_contact_at??null,notes:notes.results.map((row)=>({id:row.id,content:row.content,createdAt:row.created_at,authorName:row.author_name}))}}
export async function saveNextContact(workspaceId:string,consultationId:string,userId:string,nextContactAt:string|null){if(!await eligible(workspaceId,consultationId))return false;const db=await getDb();if(nextContactAt)await db.prepare(`INSERT INTO quote_followup_schedules(consultation_id,workspace_id,next_contact_at,updated_by_user_id) VALUES(?,?,?,?) ON CONFLICT(consultation_id) DO UPDATE SET next_contact_at=excluded.next_contact_at,updated_by_user_id=excluded.updated_by_user_id,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE workspace_id=excluded.workspace_id`).bind(consultationId,workspaceId,nextContactAt,userId).run();else await db.prepare(`DELETE FROM quote_followup_schedules WHERE consultation_id=? AND workspace_id=?`).bind(consultationId,workspaceId).run();return true}
export async function addFollowupNote(workspaceId:string,consultationId:string,userId:string,content:string){if(!await eligible(workspaceId,consultationId))return null;const db=await getDb(),id=crypto.randomUUID();await db.prepare(`INSERT INTO quote_followup_notes(id,workspace_id,consultation_id,author_user_id,content) VALUES(?,?,?,?,?)`).bind(id,workspaceId,consultationId,userId,content).run();const row=await db.prepare(`SELECT n.id,n.content,n.created_at,COALESCE(NULLIF(u.display_name,''),u.google_name,u.email,'알 수 없음') AS author_name FROM quote_followup_notes n LEFT JOIN users u ON u.id=n.author_user_id WHERE n.id=? AND n.workspace_id=?`).bind(id,workspaceId).first<{id:string;content:string;created_at:string;author_name:string}>();return row?{id:row.id,content:row.content,createdAt:row.created_at,authorName:row.author_name}:null}
export async function listTodayFollowups(workspaceId:string,dateKey:string){const result=await (await getDb()).prepare(`SELECT c.id,c.client_name,s.next_contact_at,(SELECT n.content FROM quote_followup_notes n WHERE n.workspace_id=c.workspace_id AND n.consultation_id=c.id ORDER BY n.created_at DESC,n.id DESC LIMIT 1) AS latest_note FROM quote_followup_schedules s JOIN consultations c ON c.id=s.consultation_id AND c.workspace_id=s.workspace_id WHERE s.workspace_id=? AND c.quote_status='SENT' AND c.contract_outcome='PENDING' AND substr(s.next_contact_at,1,10)=? ORDER BY s.next_contact_at,c.client_name`).bind(workspaceId,dateKey).all<{id:string;client_name:string;next_contact_at:string;latest_note:string|null}>();return result.results.map((row)=>({id:row.id,customerName:row.client_name,nextContactAt:row.next_contact_at,latestNote:row.latest_note}))}
